import { test, expect } from '@playwright/test';

// 只连接专用临时 profile 的真实服务，不允许启动任务或连接设备。
const base = 'http://127.0.0.1:18758';
test('战斗方案：选项、独立复制、排序及真实保存重载', async ({ page, request }, info) => {
  expect(process.env.WVD_STRATEGY_ISOLATED).toBe('1');
  const blocked: string[] = [];
  await page.route('**/*', async route => {
    const req = route.request(), url = new URL(req.url());
    const safe = url.origin === base && (req.method() === 'GET' ||
      (req.method() === 'PUT' && url.pathname === '/api/v1/profile'));
    if (!safe) { blocked.push(req.method() + ' ' + url.pathname); await route.abort(); }
    else await route.continue();
  });
  const catalog = await (await request.get(base + '/api/v1/catalog')).json();
  expect(catalog.skill_targets.map((v: any) => v.value)).toEqual(['左上角色', '中上角色', '右上角色', '左下角色', '中下角色', '右下角色']);
  expect(catalog.skill_frequencies.map((v: any) => v.label)).toEqual(['用完后移除', '重复该动作']);
  await page.goto(base);
  await page.getByRole('button', { name: '常用参数', exact: true }).click();
  await page.getByRole('button', { name: '新建方案', exact: true }).click();
  const name = '频次验收-' + info.project.name;
  const originalName = await page.locator('.strategy-title').innerText();
  await page.getByRole('button', { name: '重命名', exact: true }).click();
  await page.getByLabel('方案名称', { exact: true }).fill('');
  await page.getByRole('button', { name: '确认重命名', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('请输入方案名称');
  const existingName = await page.locator('.strategy-list [role=option] > span:not(.row-number)').first().innerText();
  await page.getByLabel('方案名称', { exact: true }).fill(existingName);
  await page.getByRole('button', { name: '确认重命名', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('已有同名方案，请使用其它名称');
  await page.getByLabel('方案名称', { exact: true }).fill(name);
  await page.getByRole('button', { name: '取消重命名', exact: true }).click();
  await expect(page.locator('.strategy-title')).toHaveText(originalName);
  await page.getByRole('button', { name: '重命名', exact: true }).click();
  await page.getByLabel('方案名称', { exact: true }).fill(name);
  await page.getByLabel('方案名称', { exact: true }).press('Enter');
  await expect(page.locator('.strategy-title')).toHaveText(name);
  await page.getByRole('button', { name: '新增角色技能', exact: true }).click();
  await expect(page.getByLabel('技能目标', { exact: true })).toHaveValue('左上角色');
  await expect(page.getByLabel('技能频次', { exact: true })).toHaveValue('用完后移除');
  await expect(page.getByLabel('技能目标', { exact: true }).locator('option')).toHaveCount(6);
  await expect(page.getByLabel('技能频次', { exact: true }).locator('option')).toHaveCount(2);
  await page.getByLabel('技能目标', { exact: true }).selectOption('右下角色');
  await page.getByLabel('技能频次', { exact: true }).selectOption('重复');
  const savebar = page.getByRole('region', { name: '战斗方案保存', exact: true });
  const localSave = savebar.getByRole('button', { name: '保存战斗方案', exact: true });
  await expect(localSave).toBeEnabled();
  const refreshPrompt = page.waitForEvent('dialog');
  const cancelledRefresh = page.evaluate(() => window.location.reload());
  const warning = await refreshPrompt;
  expect(warning.type()).toBe('beforeunload');
  await warning.dismiss();
  await cancelledRefresh;
  await expect(page.getByLabel('技能目标', { exact: true })).toHaveValue('右下角色');
  await localSave.click();
  await expect(page.getByText('已保存战斗方案', { exact: true })).toBeVisible();
  const saved = await (await request.get(base + '/api/v1/profile')).json();
  const row = saved.profile.STRATEGY.find((v: any) => v.group_name === name).skill_settings[0];
  expect(row.target_var).toBe('右下角色'); expect(row.freq_var).toBe('重复');
  await page.reload();
  await page.getByRole('button', { name: '常用参数', exact: true }).click();
  await page.getByRole('option', { name: name + ' 1 项', exact: true }).click();
  await expect(page.getByLabel('技能目标', { exact: true })).toHaveValue('右下角色');
  await expect(page.getByLabel('技能频次', { exact: true })).toHaveValue('重复');
  const rows = page.locator('.skill-row');
  await expect(rows.nth(0).getByRole('button', { name: '上移角色配置', exact: true })).toBeDisabled();
  await expect(rows.nth(0).getByRole('button', { name: '下移角色配置', exact: true })).toBeDisabled();
  await rows.nth(0).getByRole('button', { name: '复制角色配置', exact: true }).click();
  await expect(rows).toHaveCount(2);
  await expect(rows.nth(1).getByLabel('技能目标', { exact: true })).toHaveValue('右下角色');
  await expect(rows.nth(1).getByLabel('技能频次', { exact: true })).toHaveValue('重复');
  await rows.nth(1).getByLabel('技能等级', { exact: true }).selectOption('7');
  await rows.nth(1).getByLabel('技能频次', { exact: true }).selectOption('用完后移除');
  await rows.nth(1).getByRole('button', { name: '上移角色配置', exact: true }).click();
  await expect(rows.nth(0).getByLabel('技能等级', { exact: true })).toHaveValue('7');
  await expect(rows.nth(1).getByLabel('技能等级', { exact: true })).toHaveValue('1');
  await rows.nth(0).getByRole('button', { name: '下移角色配置', exact: true }).click();
  await expect(rows.nth(1).getByLabel('技能等级', { exact: true })).toHaveValue('7');
  await rows.nth(1).getByRole('button', { name: '上移角色配置', exact: true }).click();
  await expect(page.getByRole('button', { name: '下移方案', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '复制方案', exact: true }).click();
  await expect(page.locator('.strategy-title')).toHaveText(name + ' 副本');
  await expect(rows).toHaveCount(2);
  await rows.nth(0).getByLabel('技能目标', { exact: true }).selectOption('左上角色');
  await page.getByRole('option', { name: name + ' 2 项', exact: true }).click();
  await expect(rows.nth(0).getByLabel('技能目标', { exact: true })).toHaveValue('右下角色');
  await page.getByRole('button', { name: '复制方案', exact: true }).click();
  await expect(page.locator('.strategy-title')).toHaveText(name + ' 副本 2');
  // 在筛选视图中仍调整真实数组顺序；操作后清空筛选，选中项跟随移动。
  await page.getByRole('searchbox').fill('副本 2');
  await page.getByRole('button', { name: '上移方案', exact: true }).click();
  await expect(page.getByRole('searchbox')).toHaveValue('');
  await expect(page.locator('.strategy-title')).toHaveText(name + ' 副本 2');
  await page.getByRole('button', { name: '下移方案', exact: true }).click();
  await page.getByRole('button', { name: '下移方案', exact: true }).click();
  await expect(page.getByRole('button', { name: '下移方案', exact: true })).toBeDisabled();
  const firstName = await page.locator('.strategy-list [role=option] > span:not(.row-number)').first().innerText();
  await page.locator('.strategy-list [role=option]').first().click();
  await expect(page.locator('.strategy-title')).toHaveText(firstName);
  await expect(page.getByRole('button', { name: '上移方案', exact: true })).toBeDisabled();
  await page.getByRole('option', { name: name + ' 副本 2 2 项', exact: true }).click();
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  const saveBox = await localSave.boundingBox();
  expect(saveBox).not.toBeNull();
  expect(saveBox!.y).toBeGreaterThanOrEqual(0);
  expect(saveBox!.y + saveBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  await page.getByRole('button', { name: '保存战斗方案', exact: true }).click();
  await expect(page.getByText('已保存战斗方案', { exact: true })).toBeVisible();
  const after = await (await request.get(base + '/api/v1/profile')).json();
  const groups = after.profile.STRATEGY;
  expect(groups.slice(-3).map((g: any) => g.group_name)).toEqual([name, name + ' 副本', name + ' 副本 2']);
  for (const group of groups.slice(-3)) {
    expect(group.skill_settings.map((s: any) => s.skill_lvl)).toEqual([7, 1]);
    expect(group.skill_settings.map((s: any) => s.freq_var)).toEqual(['用完后移除', '重复']);
  }
  expect(groups.at(-2).skill_settings[0].target_var).toBe('左上角色');
  expect(groups.at(-1).skill_settings[0].target_var).toBe('右下角色');
  const { STRATEGY: _beforeGroups, ...beforeFields } = saved.profile;
  const { STRATEGY: _afterGroups, ...afterFields } = after.profile;
  expect(afterFields).toEqual(beforeFields);
  expect(groups.slice(0, -3)).toEqual(saved.profile.STRATEGY.slice(0, -1));
  await page.reload();
  await page.getByRole('button', { name: '常用参数', exact: true }).click();
  await page.getByRole('option', { name: name + ' 副本 2 2 项', exact: true }).click();
  await expect(rows.nth(0).getByLabel('技能等级', { exact: true })).toHaveValue('7');
  await expect(rows.nth(1).getByLabel('技能等级', { exact: true })).toHaveValue('1');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await rows.nth(0).getByRole('button', { name: '复制角色配置', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('strategy-frequency.png'), fullPage: true });
  expect(blocked).toEqual([]);
});
